//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RISING.STAR.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public System.Guid DocumentId { get; set; }
        public System.Guid PatientId { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> DeleteMoveDate { get; set; }
        public string DeleteMoveBy { get; set; }
        public Nullable<System.Guid> MovedToPatientId { get; set; }
        public Nullable<int> DimX { get; set; }
        public Nullable<int> DimY { get; set; }
        public byte[] PatientDoc { get; set; }
    
        public virtual Patients_Table Patients_Table { get; set; }
        public virtual Patients_Table Patients_Table1 { get; set; }
    }
}
