//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RISING.STAR.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETDRSNearVA
    {
        public System.Guid ETDRSID { get; set; }
        public string ETDRSVA { get; set; }
        public double LogMar { get; set; }
        public double LetterSize { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
