//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RISING.STAR.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exams_Table
    {
        public System.Guid Id { get; set; }
        public System.Guid PatientId { get; set; }
        public System.DateTime DateInserted { get; set; }
        public System.DateTime DateExam { get; set; }
        public float OD_Sph { get; set; }
        public float OD_Cyl { get; set; }
        public short OD_Axis { get; set; }
        public float OS_Sph { get; set; }
        public float OS_Cyl { get; set; }
        public short OS_Axis { get; set; }
    
        public virtual Patients_Table Patients_Table { get; set; }
    }
}
