//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RISING.STAR.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterventionEvent
    {
        public System.Guid InterventionEventGuid { get; set; }
        public System.Guid PatientGuid { get; set; }
        public System.Guid InterventionTypeGuid { get; set; }
        public string Eye { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual InterventionType InterventionType { get; set; }
        public virtual Patients_Table Patients_Table { get; set; }
    }
}
