//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RISING.STAR.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterventionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InterventionType()
        {
            this.InterventionEvents = new HashSet<InterventionEvent>();
        }
    
        public System.Guid InterventionGuid { get; set; }
        public Nullable<System.Guid> CategoryGuid { get; set; }
        public string Description { get; set; }
        public System.Guid IconGuid { get; set; }
    
        public virtual InterventionCategory InterventionCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterventionEvent> InterventionEvents { get; set; }
        public virtual InterventionIcon InterventionIcon { get; set; }
    }
}
