//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RISING.STAR.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientsComment
    {
        public System.Guid CommentId { get; set; }
        public System.Guid PatientId { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid DoctorId { get; set; }
    
        public virtual Patients_Table Patients_Table { get; set; }
        public virtual User User { get; set; }
    }
}
