//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RISING.STAR.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients_Table()
        {
            this.Acquisitions_Table = new HashSet<Acquisitions_Table>();
            this.Exams_Table = new HashSet<Exams_Table>();
        }
    
        public int Id { get; set; }
        public System.Guid Guid { get; set; }
        public string NAME { get; set; }
        public string SURNAME1 { get; set; }
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string SEX { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string ZIP { get; set; }
        public string COUNTRY { get; set; }
        public string PHONE { get; set; }
        public string E_MAIL { get; set; }
        public string OBSERVATIONS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acquisitions_Table> Acquisitions_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exams_Table> Exams_Table { get; set; }
    }
}
